#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/access_control
#
# IDENTIFICATION
#    src/backend/access_control/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access_control
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = context.o oacp.o

include $(top_srcdir)/src/backend/common.mk