#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/access_control
#
# IDENTIFICATION
#    src/backend/access_control/Makefile
# 
# USAGE
# 	 To use another access control algorithm, just replace the oacp.o with 
#	 desired implementation
#-------------------------------------------------------------------------

subdir = src/backend/access_control
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = test.o context.o
#oacp.o

include $(top_srcdir)/src/backend/common.mk